---

- name:  Install telegraf config file
  template:
    src: "telegraf_conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    backup: yes
    group: root
    mode: 0644
  notify: Restart telegraf daemon