---

- name:  Delete configuration HAVP directories for each revoked domain
  file:
      path: "{{ v_havp_root_directory }}/{{ item.domain }}"
      state: absent
  with_items: "{{ revoked_domains }}"
  notify: 
    - Stop havp daemon
