---

- name:  Install filebeat config file
  template:
    src: "grant/filebeat_yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    backup: yes
    group: root
    mode: 0640
  with_items: 
     - "{{ granted_domains }}"
     - "{{ ec2_low_met_private_dns_names }}"
  notify: Restart filebeat daemon
