---

- name:  Create filebeat directory 
  file:
      path: "{{ v_log_path }}/filebeat"
      state: directory
      mode: 0755

- name:  Install filebeat config file
  template:
    src: "filebeat_yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    backup: yes
    group: root
    mode: 0640
  with_items:
     - "{{ ec2_low_met_private_dns_names }}"
  notify: Restart filebeat daemon
