---

- name: Install nginx softwares
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - nginx-all-modules
    - nginx-mod-stream

- name: Add configuration file to nginx directory
  template:
    src: "init/nginx.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
