---

- name: Disable httpd daemon
  systemd:
    name: httpd
    enabled: no
    state: stopped
    no_block: yes
    force: yes
  ignore_errors: true

- name: Disable firewalld daemon
  systemd:
    name: firewalld
    enabled: no
    state: stopped
    no_block: yes
    force: yes
  ignore_errors: true

- name: Restart filebeat daemon
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
  ignore_errors: true

- name: Reload haproxy daemon
  systemd:
    name: haproxy
    enabled: yes
    state: reloaded
  ignore_errors: true

- name: Start haproxy daemon
  systemd:
    name: haproxy
    enabled: yes
    state: restarted
  ignore_errors: true

- name: Reload iptables daemon
  systemd:
    name: iptables
    enabled: yes
    state: reloaded
  ignore_errors: true  

- name: Restart telegraf daemon
  systemd:
    name: telegraf
    enabled: yes
    state: restarted
  ignore_errors: true