---

- name: Groupinstall Development tools
  shell: yum groupinstall 'Development tools'

- name: Install Development Tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - bzip2
    - flex
    - gcc
    - git
    - httpd-devel
    - libaio-devel
    - libass-devel
    - libjpeg-turbo-devel
    - libpng12-devel
    - libtheora-devel
    - libtool
    - libva-devel
    - libvdpau-devel
    - libvorbis-devel
    - libxml2-devel
    - libxslt-devel
    - perl
    - texi2html
    - unzip
    - zip
    - openssl
    - openssl-devel
    - geoip
    - geoip-devel

- name: Download and Install libModSecurity
  shell: |
    cd /opt/
    git clone https://github.com/SpiderLabs/ModSecurity
    cd ModSecurity
    git checkout -b v3/master origin/v3/master
    sh build.sh
    git submodule init
    git submodule update
    ./configure
    make
    make install
    make check

- name: Download the ModSecurity Nginx connector
  shell: |
    cd /opt/
    git clone https://github.com/SpiderLabs/ModSecurity-nginx.git

- name: Download and Install Nginx 1.16.0
  shell: |
    cd /opt/
    wget http://nginx.org/download/nginx-1.16.0.tar.gz
    tar xvzf nginx-1.16.0.tar.gz
    cd nginx-1.16.0
    ./configure --user=www-data --group=www-data --with-pcre-jit --with-debug --with-http_ssl_module --with-http_realip_module --add-module=/opt/ModSecurity-nginx
    make
    make install
    cp /opt/ModSecurity/modsecurity.conf-recommended /usr/local/nginx/conf/modsecurity.conf
    ln -s /usr/local/nginx/sbin/nginx /bin/nginx

- name: Install OWASP Core Rule Set (CRS)
  shell: |
    cd /opt/
    git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git
    cd owasp-modsecurity-crs/
    cp -R rules/ /usr/local/nginx/conf/
    cp /opt/owasp-modsecurity-crs/crs-setup.conf.example /usr/local/nginx/conf/crs-setup.conf

- name:  Install clamav (antivirus) softwares
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - clamav
    - clamav-data
    - clamav-filesystem
    - clamav-scanner
    - clamav-server
    - clamav-server-systemd
    - clamav-update
