heat_template_version: '2018-08-31'

description: CIAP load balancer

#>===========================================================================<#
#>=======                         Parameters                          =======<#
#>===========================================================================<#
parameters:
  name:
    type: string
    description: Servers name

  image:
    type: string
    description: Image used by the servers

  flavor:
    type: string
    description: Flavor desired

  ssh_user:
    type: string
    description: SSH User to connect to the servers

  ssh_authorized_key:
    type: string
    description: SSH Key to connect to the servers

  network:
    type: string
    description: Network used by the servers

  subnet:
    type: string
    description: Subnet used by the servers

  metadata:
    default: {}
    type: json

#>===========================================================================<#
#>=======                          Resources                          =======<#
#>===========================================================================<#
resources:
  server_group_id:
    type: OS::Heat::RandomString

  servers:
    type: OS::Heat::AutoScalingGroup
    properties:
      desired_capacity: 1
      min_size: 1
      max_size: 3
      cooldown: 300
      resource:
        type: load-balancer-server.yaml
        properties:
          name: { get_param: name }
          flavor: { get_param: flavor }
          image: { get_param: image }
          ssh_user: { get_param: ssh_user }
          ssh_authorized_key: { get_param: ssh_authorized_key }
          network: { get_param: network }
          subnet: { get_param: subnet }
          pool_http: { get_resource: pool_http }
          pool_https: { get_resource: pool_https }
          metadata: { map_merge: [{
            'metering.server_group': { get_resource: server_group_id },
            'ssh_user': { get_param: ssh_user }
          }, { get_param: metadata } ]}

  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: servers }
      cooldown: 300
      scaling_adjustment: 1

  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: servers }
      cooldown: 300
      scaling_adjustment: -1

  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale up if CPU > 80% for 5 minutes
      metric: cpu_util
      aggregation_method: mean
      granularity: 600
      evaluation_periods: 1
      threshold: 80
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: { get_attr: [scaleup_policy, signal_url] }
      query:
        str_replace:
          template: '{"=": {"server_group": "$ID"}}'
          params:
            $ID: { get_resource: server_group_id }

  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale down if CPU < 15% for 5 minutes
      metric: cpu_util
      aggregation_method: mean
      granularity: 600
      evaluation_periods: 1
      threshold: 15
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: { get_attr: [scaledown_policy, signal_url] }
      query:
        str_replace:
          template: '{"=": {"server_group": "$ID"}}'
          params:
            $ID: { get_resource: server_group_id }

  lb:
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: { get_param: subnet }

  listener_http:
    type: OS::Octavia::Listener
    properties:
      loadbalancer: { get_resource: lb }
      protocol: HTTP
      protocol_port: 80

  pool_http:
    type: OS::Octavia::Pool
    properties:
      listener: { get_resource: listener_http }
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      session_persistence:
        type: SOURCE_IP

  lb_monitor_http:
    type: OS::Octavia::HealthMonitor
    properties:
      pool: { get_resource: pool_http }
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5

  listener_https:
    type: OS::Octavia::Listener
    properties:
      loadbalancer: { get_resource: lb }
      protocol: HTTPS
      protocol_port: 443

  pool_https:
    type: OS::Octavia::Pool
    properties:
      listener: { get_resource: listener_https }
      lb_algorithm: ROUND_ROBIN
      protocol: HTTPS
      session_persistence:
        type: SOURCE_IP

  lb_monitor_https:
    type: OS::Octavia::HealthMonitor
    properties:
      pool: { get_resource: pool_https }
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5

#>===========================================================================<#
#>=======                           Outputs                           =======<#
#>===========================================================================<#
outputs:
  lb_address:
    value: { get_attr: [ lb, vip_address ] }
  lb_port_id:
    value: { get_attr: [ lb, vip_port_id ] }

