---

- name: Search certificats
  stat:
    path: "{{ v_certificates_path }}/{{ item.domain }}.key"
  when: item.domain is defined
  with_items:
    - "{{ granted_domains }}"
  register: mid_waf_key_certificats

- name: Generate ssl certificates
  command: "openssl req -x509 -nodes -newkey rsa:2048 -keyout {{ v_certificates_path }}/{{ item.item.domain }}.key -out {{ v_certificates_path }}/{{ item.item.domain }}.crt -days 3650 -subj /CN={{ item.item.domain }}/"
  args:
    chdir: "{{ v_certificates_path }}"
    creates: "certificates"
  when:
    - item.stat is defined
    - item.stat.exists == False
  with_items: "{{ mid_waf_key_certificats.results }}"
