---

- name: Install telegraf config file
  template:
    src: "telegraf_conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    backup: yes
    group: telegraf
    mode: 0640
  when: item.domain is defined
  with_items:
    - "{{ granted_domains }}"
  notify: Restart telegraf daemon
