---

- name: Copy openssl client extensions
  copy:
    src: openssl-client.ext
    dest: "{{ openvpn_key_dir }}"
    owner: root
    group: root
    backup: yes
    force: yes
    mode: 0400

- name: Generate client key
  command: openssl req -nodes -newkey rsa:{{ openvpn_rsa_bits }} -keyout {{ ciap }}-{{ item.email }}.key -out {{ ciap }}-{{ item.email }}.csr -days 3650 -subj /CN={{ openvpn_x509_client_name_prefix }}{{ item.email[:24] }}/
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ ciap }}-{{ item.email }}.key"
  with_items: 
    - "{{ openvpn_grant_clients }}"

- name: Protect client keys
  file:
    path: "{{ openvpn_key_dir }}/{{ ciap }}-{{ item.email }}.key"
    mode: 0400
  with_items: 
    - "{{ openvpn_grant_clients }}"

- name: Sign client key
  command: openssl x509 -req -in {{ ciap }}-{{ item.email }}.csr -out {{ ciap }}-{{ item.email }}.crt -CA {{ openvpn_ca_crt_name }} -CAkey {{ openvpn_ca_key_name }} -sha256 -days {{ openvpn_ca_validity_days }} -extfile openssl-client.ext
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ ciap }}-{{ item.email }}.crt"
  with_items: 
    - "{{ openvpn_grant_clients }}"

- name: Register server ca key
  slurp:
    src: "{{ openvpn_key_dir }}/{{ openvpn_ca_crt_name }}"
  register: ca_cert

- name: Register tls-auth key
  slurp:
    src: "{{ openvpn_key_dir }}/{{ openvpn_ta_key_name }}"
  register: tls_auth

- name: Register client certs
  slurp:
    src: "{{ openvpn_key_dir }}/{{ ciap }}-{{ item.email }}.crt"
  with_items: "{{ openvpn_grant_clients }}"
  register: client_certs

- name: Register client keys
  slurp:
    src: "{{ openvpn_key_dir }}/{{ ciap }}-{{ item.email }}.key"
  with_items: "{{ openvpn_grant_clients }}"
  register: client_keys

- name: Generate client config
  template:
    src: client.ovpn.j2
    dest: "{{ openvpn_ovpn_dir }}/{{ ciap }}-{{ item.email }}.ovpn"
    owner: root
    group: root
    force: yes
    mode: 0400
  with_items: 
    - "{{ openvpn_grant_clients }}"

- name: Generate ccd client config
  template:
    src: client.ccd.j2
    dest: "{{ openvpn_ccd_dir }}/{{ ciap }}-{{ item.email }}"
    owner: root
    group: root
    force: yes
    mode: 0444
  with_items: 
    - "{{ openvpn_grant_clients }}"

- name: Fetch client config
  fetch:
    src: "{{ openvpn_ovpn_dir }}/{{ ciap }}-{{ item.email }}.ovpn"
    dest: "/tmp/ansible/{{ ciap }}-{{ item.email }}/{{ inventory_hostname }}.ovpn"
    force: yes
    flat: yes
  with_items:
    - "{{ openvpn_grant_clients }}"

- name: Generate client archive
  archive:
    path:
        - "{{ openvpn_key_dir }}/{{ ciap }}-{{ item.email }}.key"
        - "{{ openvpn_key_dir }}/{{ ciap }}-{{ item.email }}.crt"
        - "{{ openvpn_ovpn_dir }}/{{ ciap }}-{{ item.email }}.ovpn"
        - "{{ openvpn_key_dir }}/ca.crt"
        - "{{ openvpn_key_dir }}/ta.key"
    dest: "/{{ openvpn_clients_dir }}/{{ ciap }}-{{ item.email }}.zip"
    force: yes
    format: zip
  with_items: 
    - "{{ openvpn_grant_clients }}"
