---

- name: Add domains
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "domains.yml"
      skip: true
  tags: [always]

- import_tasks: init/softwares.yml
  tags:
   - init
   - common

- import_tasks: init/selinux.yml
  tags:
   - init
   - common

- import_tasks: init/haproxy_healthcheck.yml
  tags:
   - init
   - common

- import_tasks: init/ssl.yml
  tags:
   - init
   - common
