---

- name: Add the MariaDB repository
  copy:
    src: maria_db.repo
    dest: /etc/yum.repos.d/maria_db.repo
    owner: root
    group: root
    mode: 0400
    backup: yes
    force: yes

- name: Install MariaDB
  package: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - python2-PyMySQL

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Start MariaDB Service
  service: name=mysqld state=started enabled=yes

- name: Create Wordpress database
  mysql_db: name="{{ wp_db_name }}" state=present

- name: Create Wordpress user
  mysql_user: 
    name="{{ wp_db_user }}"
    password="{{ wp_db_password }}"
    priv=*.*:ALL
