---

- name: Install softwares
  package: name={{ item }} state=present
  with_items:
    - nginx
    - openssl

- name: Add remi-php72
  yum_repository:
    name: remi-php72
    description: Remi's PHP 7.2 RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php72/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
  
- name: Install PHP 7.2
  package: name={{ item }} state=present
  with_items:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-fpm

- name: Check if Strong Dh file exists
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: strong_dh_file_check

- name: Generate Strong Dh (Diffie-Hellman)
  when: not strong_dh_file_check.stat.exists
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

- name: Check if Self-Signed Certificate exists
  stat:
    path: /etc/ssl/certs/wordpress.key
  register: certificate_file_check

- name: Create Self-Signed Certificate
  when: not certificate_file_check.stat.exists
  shell: openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/certs/wordpress.key -out /etc/ssl/certs/wordpress.cert -nodes -days 365 -subj '/CN=localhost'

- name: Nginx configuration
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  run_once: true
  notify: Reload nginx daemon

- name: Nginx vhost
  template:
    src: nginx-vhost.j2
    dest: /etc/nginx/conf.d/plug.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  run_once: true
  notify: Reload nginx daemon
