---

- name: Change default admin password
  uri:
    url: http://localhost:3000/api/user/password
    method: PUT
    user: admin
    password: admin
    body: "{ \"oldPassword\": \"admin\", \"newPassword\": \"{{ v_grafana_admin_password }}\", \"confirmNew\": \"{{ v_grafana_admin_password }}\" }"
    force_basic_auth: yes
    status_code: 200
    validate_certs: no
    timeout: 5
    body_format: json
  notify: Enable and restart grafana systemd service
