---

- name:  Install grafana config file
  template:
    src: "grafana/grafana_ini.j2"
    dest: "/etc/grafana/grafana.ini"
    owner: root
    backup: yes
    group: grafana
    mode: 0640
  notify: Enable and restart grafana systemd service

