---

- name: Search certificats
  stat:
    path: "{{ v_certificates_path }}/{{ item.domain }}.key"
  with_items:
    - "{{ granted_domains }}"
  register: mid_waf_key_certificats

- name: Generate ssl certificates
  command: "openssl req -x509 -nodes -newkey rsa:2048 -keyout {{ v_certificates_path }}/{{ item.item.domain }}.key -out {{ v_certificates_path }}/{{ item.item.domain }}.crt -days 3650 -subj /CN={{ item.item.domain }}/"
  args:
    chdir: "{{ v_certificates_path }}"
    creates: "certificates"
  when:
    - item.stat.exists == False
  with_items: "{{ mid_waf_key_certificats.results }}"

- name: Add domain configuration files to nginx directory
  template:
    src: "grant/nginx_vhost.j2"
    dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
    owner: root
    force: yes
    group: root
    mode: 0644
    backup: yes
  with_items:
    - "{{ granted_domains }}"
  notify: Reload nginx daemon

- name: Create log nginx directories for each domain
  file:
    path: "{{ v_log_path }}/nginx/{{ item.domain }}/"
    state: directory
    mode: 0755
  with_items:
    - "{{ granted_domains }}"
  notify: Reload nginx daemon
