---

- name: Nginx configuration
  template:
    src: "grant/nginx_conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - "{{ granted_domains }}"
  notify: Reload nginx daemon
