---

- name:  Install telegraf config file
  template:
    src: "grant/telegraf_conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    owner: root
    backup: yes
    group: root
    mode: 0644
  when: item.domain is defined
  with_items:
    - "{{ granted_domains }}"
  notify: Restart telegraf daemon
