---

- name: Add domain configuration files to haproxy directory
  template:
    src: "haproxy.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    backup: yes
    force: yes
    group: root
    mode: 0644
  when: item.domain is defined
  with_items: 
    - "{{ granted_domains }}"
  notify: Reload haproxy daemon
