---

- name: Restart nginx daemon
  systemd:
    name: "nginx"
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Reload nginx daemon
  systemd:
    name: "nginx"
    enabled: yes
    state: reloaded
    no_block: yes
  ignore_errors: true

- name: Reload iptables daemon
  systemd:
    name: "iptables"
    enabled: yes
    state: reloaded
    no_block: yes
  ignore_errors: true

- name: Reload rsyslog daemon
  systemd:
    name: "rsyslog"
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Restart filebeat daemon
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Restart telegraf daemon
  systemd:
    name: telegraf
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true
