---

- name: Remove firewalld software
  package:
    name: firewalld
    state: absent
  notify: Disable firewalld daemon

- name: Remove postfix software
  package:
    name: postfix
    state: absent
  notify: Disable postfix daemon

- name: Install epel-release
  package:
    name: epel-release
    state: present

- name: Install editors
  package: name={{item}} state=present
  with_items:
    - vim-enhanced
    - emacs-nox
    - nano

- name: Install Python 3.6
  package: name={{item}} state=present
  with_items:
    - python36
    - python36-pip
    - python36-wheel
    - python36-devel
    - python36-virtualenv
