---

- name: restart openvpn
  service:
    name: "{{openvpn_service_name}}"
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Reload iptables daemon
  service:
    name: iptables
    state: reloaded
    no_block: yes
  ignore_errors: true

- name: Restart iptables daemon
  service:
    name: iptables
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Restart filebeat daemon
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true

- name: Restart telegraf daemon
  systemd:
    name: telegraf
    enabled: yes
    state: restarted
    no_block: yes
  ignore_errors: true