---

- name: Delete configuration HAVP directories for each revoked domain
  file:
    path: "{{ v_havp_root_directory }}/{{ item.domain }}"
    state: absent
  when: item.domain is defined
  with_items: "{{ revoked_domains }}"
  notify: 
    - Stop havp daemon
