---

- name:  Add HaProxy configuration file to rsyslog directory
  template:
    src: "rsyslog_haproxy.j2"
    dest: "/etc/rsyslog.d/haproxy.conf"
    owner: root
    backup: yes
    force: yes
    group: root
    mode: 0644
  notify: Reload rsyslog daemon
