---

- name: Restart clamd daemon
  systemd:
    name: clamdscan
    daemon_reload: yes
    enabled: yes
    no_block: yes
    state: restarted
  ignore_errors: true

- name: Restart havp daemon
  systemd:
    name: "havp.{{ item.domain }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
    no_block: yes
  with_items: "{{ granted_domains }}"
  when: item.domain in restart_havp_daemons | default([])
  ignore_errors: true

- name: Restart SURICATA daemon
  systemd:
    name: "suricata.{{ item.domain }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
    no_block: yes
  with_items: "{{ granted_domains }}"
  when: item.domain in restart_suricata_daemons | default([])
  ignore_errors: true

- name: Stop havp daemon
  systemd:
    name: "havp.{{ item.domain }}"
    enabled: no
    state: stopped
    no_block: yes
  with_items: "{{ revoked_domains }}"
  notify: 
    - Remove HAVP daemon configuration
  ignore_errors: true

- name: Remove HAVP daemon configuration
  file:
    dest: "/etc/systemd/system/havp.{{ item.domain }}.service"
    state: absent
  with_items: "{{ revoked_domains }}"
  ignore_errors: true

- name: Stop SURICATA daemon
  systemd:
    name: "suricata.{{ item.domain }}"
    enabled: no
    state: stopped
    no_block: yes
  with_items: "{{ revoked_domains }}"
  notify: 
    - Remove SURICATA daemon configuration
  ignore_errors: true

- name: Remove SURICATA daemon configuration
  file:
    path: "/etc/systemd/system/suricata.{{ item.domain }}.service"
    state: absent
  with_items: "{{ revoked_domains }}"
  ignore_errors: true

- name: Reload nginx daemon
  systemd:
    name: "nginx"
    daemon_reload: yes
    enabled: yes
    state: reloaded
    no_block: yes
  ignore_errors: true

- name: Reload iptables daemon
  systemd:
    name: iptables
    enabled: yes
    state: reloaded
    no_block: yes
  ignore_errors: true
