---

- name: Setup plug
  hosts: plug
  become: yes
  gather_facts: yes
  roles:
    - common
    - plug

- name: Setup Mid Waf
  hosts: mid-waf
  become: yes
  gather_facts: yes
  roles:
    - common
    - mid_waf

- name: Setup UP LB
  hosts: up-lb
  become: yes
  gather_facts: yes
  roles:
    - common
    - up_lb

#- name: Setup Low Met
#  hosts: low-met
#  become: yes
#  gather_facts: yes
#  roles:
#    - common

- name: Setup Low Fw
  hosts: low-fw
  become: yes
  gather_facts: yes
  roles:
    - common
    - low_fw
