---

- name: Setup plug
  hosts: plug
  become: yes
  gather_facts: yes
  roles:
    - common
    - plug
    
- name: Setup Mid Waf
  hosts: mid-waf
  become: yes
  gather_facts: yes
  roles:
    - common
    - mid-waf
